namespace AutoBot_v1._Bot
{
    public class KeywordParser
    {
        public static readonly Keyword[] Keys = new Keyword[]
        {
            new Keyword(' ', _Keys.KeyBotEnum.Space),
            new Keyword('a', _Keys.KeyBotEnum.A),
            new Keyword('b', _Keys.KeyBotEnum.B),
            new Keyword('c', _Keys.KeyBotEnum.C),
            new Keyword('d', _Keys.KeyBotEnum.D),
            new Keyword('e', _Keys.KeyBotEnum.E),
            new Keyword('f', _Keys.KeyBotEnum.F),
            new Keyword('g', _Keys.KeyBotEnum.G),
            new Keyword('h', _Keys.KeyBotEnum.H),
            new Keyword('i', _Keys.KeyBotEnum.I),
            new Keyword('j', _Keys.KeyBotEnum.J),
            new Keyword('k', _Keys.KeyBotEnum.K),
            new Keyword('l', _Keys.KeyBotEnum.L),
            new Keyword('m', _Keys.KeyBotEnum.M),
            new Keyword('n', _Keys.KeyBotEnum.N),
            new Keyword('o', _Keys.KeyBotEnum.O),
            new Keyword('p', _Keys.KeyBotEnum.P),
            new Keyword('q', _Keys.KeyBotEnum.Q),
            new Keyword('r', _Keys.KeyBotEnum.R),
            new Keyword('s', _Keys.KeyBotEnum.S),
            new Keyword('t', _Keys.KeyBotEnum.T),
            new Keyword('u', _Keys.KeyBotEnum.U),
            new Keyword('v', _Keys.KeyBotEnum.V),
            new Keyword('w', _Keys.KeyBotEnum.W),
            new Keyword('x', _Keys.KeyBotEnum.X),
            new Keyword('y', _Keys.KeyBotEnum.Y),
            new Keyword('z', _Keys.KeyBotEnum.Z),
            new Keyword('A', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.A),
            new Keyword('B', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.B),
            new Keyword('C', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.C),
            new Keyword('D', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.D),
            new Keyword('E', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.E),
            new Keyword('F', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.F),
            new Keyword('G', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.G),
            new Keyword('H', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.H),
            new Keyword('I', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.I),
            new Keyword('J', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.J),
            new Keyword('K', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.K),
            new Keyword('L', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.L),
            new Keyword('M', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.M),
            new Keyword('N', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.N),
            new Keyword('O', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.O),
            new Keyword('P', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.P),
            new Keyword('Q', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.Q),
            new Keyword('R', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.R),
            new Keyword('S', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.S),
            new Keyword('T', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.T),
            new Keyword('U', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.U),
            new Keyword('V', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.V),
            new Keyword('W', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.W),
            new Keyword('X', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.X),
            new Keyword('Y', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.Y),
            new Keyword('Z', _Keys.KeyBotEnum._ShiftL, _Keys.KeyBotEnum.Z),
            new Keyword('0', _Keys.KeyBotEnum.Number0),
            new Keyword('1', _Keys.KeyBotEnum.Number1),
            new Keyword('2', _Keys.KeyBotEnum.Number2),
            new Keyword('3', _Keys.KeyBotEnum.Number3),
            new Keyword('4', _Keys.KeyBotEnum.Number4),
            new Keyword('5', _Keys.KeyBotEnum.Number5),
            new Keyword('6', _Keys.KeyBotEnum.Number6),
            new Keyword('7', _Keys.KeyBotEnum.Number7),
            new Keyword('8', _Keys.KeyBotEnum.Number8),
            new Keyword('9', _Keys.KeyBotEnum.Number9),
        };
    }
}
